---
title: "Ternary plot for metabolites"
output: html_document
---

A ternary plot using sample means.

```{r}
if(!"ggtern" %in% installed.packages(fields="Package"))
  install.packages("ggtern")
```

```{r}
library(tidyverse)
library(ggtern)
```

## get and wrangle metabolite data
```{r}
met_raw <-read_csv("../input/metabolites_set1.csv")
met <- met_raw %>% 
  mutate(sampleID=str_c("wyo", genotype, pot, sep="_")) %>%
  mutate(trt=ifelse(is.na(autoclave), "BLANK", autoclave)) %>%
  select(sampleID, pot, genotype, tissue, trt, sample_mass = `sample_mass mg`, !submission_number:concatenate)  %>%
  
  #make long
  pivot_longer(!sampleID:sample_mass, names_to = "metabolite", values_to = "met_amount") %>%
  
  #filter away unnamed
  filter(str_detect(metabolite, pattern="^[0-9]+$", negate=TRUE)) %>%
  
  # remove the outlier
  filter(!(sampleID=="wyo_FPsc_016" & tissue=="root")) %>%
  
  #adjust by sample mass
  mutate(met_per_mg=met_amount/sample_mass) %>%
  
  # got normalized and raw measurements in same column
  
  pivot_longer(c(met_amount, met_per_mg), names_to = "type", values_to = "amount") %>%
  mutate(type=ifelse(type=="met_amount", "raw", "normalized")) %>%
  
  arrange(metabolite, type, tissue, trt, genotype)

met %>% head 
```

### calculate means

```{r}
normalized.means <- met %>%
  filter(type=="normalized") %>%
  select(genotype, tissue, trt, metabolite, amount) %>%
  group_by(genotype, tissue, trt, metabolite) %>%
  summarize(value=mean(amount, na.rm = TRUE))

normalized.means
  
```

```{r}
raw.means <- met %>%
  filter(type=="raw") %>%
  select(genotype, tissue, trt, metabolite, amount) %>%
  group_by(genotype, tissue, trt, metabolite) %>%
  summarize(value=mean(amount, na.rm = TRUE))

raw.means
```


## Get pvals 

```{r}
pvals.norm <- read_csv("../output/met_per_mg_lm_full.csv") %>%
  select(metabolite, tissue, FDR_microbe=FDR_trt_trtlive, FDR_leaf=FDR_leaf_value_scale)

pvals.raw <- read_csv("../output/met_amt_lm_full.csv")  %>%
  select(metabolite, tissue, FDR_microbe=FDR_trt_trtlive, FDR_leaf=FDR_leaf_value_scale)
```

Join pvals and means

```{r}
normalized.means <- normalized.means %>% ungroup() %>% left_join(pvals.norm)

raw.means <- raw.means %>% ungroup() %>% left_join(pvals.raw)
```


## On to ternary plot

### calculate proportion of total

```{r}
met_plot_norm <- normalized.means %>%
  group_by(metabolite, genotype, tissue) %>%
  
  #proportion of total
  mutate(prop_total = value /sum(value)) %>%
  
  #reformat
  pivot_wider(id_cols = c(genotype, tissue, metabolite, FDR_microbe, FDR_leaf), 
              names_from = trt, 
              values_from = prop_total) %>%
  arrange(metabolite, tissue, genotype) %>%
  mutate(sig_microbe = FDR_microbe < 0.1,
         sig_leaf = FDR_leaf < 0.1)

met_plot_norm %>% head(20)
```


```{r}
met_plot_raw <- raw.means %>%
  group_by(metabolite, genotype, tissue) %>%
  
  #proportion of total
  mutate(prop_total = value /sum(value)) %>%
  
  #reformat
  pivot_wider(id_cols = c(genotype, tissue, metabolite, FDR_microbe, FDR_leaf), 
              names_from = trt, 
              values_from = prop_total) %>%
  arrange(metabolite, tissue, genotype) %>%
  mutate(sig_microbe = FDR_microbe < 0.1,
         sig_leaf = FDR_leaf < 0.1)

met_plot_raw %>% head(20)
```

```{r, fig.width=10, fig.height=10}
met_plot_raw %>%
  select(tissue, 
         genotype, 
         sig_microbe,
         sig_leaf,
         L=live,
         D=dead,
         B=BLANK) %>%
  arrange(sig_leaf, sig_microbe) %>%
  
  ggtern(aes(B, L, D)) +
  geom_point(aes(color=sig_microbe, shape=sig_leaf, alpha=(sig_microbe|sig_leaf))) +
  scale_color_manual(values=c("TRUE" = "red", "FALSE" = "black")) +
  scale_shape_manual(values=c("TRUE" = 17, "FALSE" = 16)) +
  scale_alpha_manual(values=c("TRUE" = 1, "FALSE" = 0.2), guide = "none") +
  facet_grid(tissue ~ genotype) + ggtitle("Not standardized") + theme_bw() 
ggsave("../../_Paper_Figures/Fig_6.png", height = 6.5, width = 6.5)
ggsave("~/Library/CloudStorage/GoogleDrive-jnmaloof@ucdavis.edu/Shared drives/BrassicaMicrobeRNAseq/Figs and Tables/Fig_6.png", height = 6.5, width = 6.5)

```

```{r, fig.width=10, fig.height=10}
met_plot_norm %>%
  select(tissue, 
         genotype, 
         sig_microbe,
         sig_leaf,
         L=live,
         D=dead,
         B=BLANK) %>%
  arrange(sig_leaf, sig_microbe) %>%
  
  ggtern(aes(B, L, D)) +
  geom_point(aes(color=sig_microbe, shape=sig_leaf, alpha=(sig_microbe|sig_leaf))) +
  scale_color_manual(values=c("TRUE" = "red", "FALSE" = "black")) +
  scale_shape_manual(values=c("TRUE" = 17, "FALSE" = 16)) +
  scale_alpha_manual(values=c("TRUE" = 1, "FALSE" = 0.2), guide = "none") +
  facet_grid(tissue ~ genotype) + ggtitle("Standardized") + theme_bw() 
ggsave("../../_Paper_Figures/Figure_S4.png", height = 6.5, width = 6.5)
ggsave("~/Library/CloudStorage/GoogleDrive-jnmaloof@ucdavis.edu/Shared drives/BrassicaMicrobeRNAseq/Figs and Tables/Fig_S4.png", height = 6.5, width = 6.5)

```