---
title: "Bayes leaf length from metab + trt"
output: html_notebook
---

---
title: "Direct Penalized Regression--Metabolites"
author: "Julin Maloof"
date: "3/09/2021"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Goal: try Bayesian approach and compare models with metabolites +/- trt

```{r}
library(tidyverse)
library(brms)
```

get leaflength data
```{r}
leaflength <- read_csv("../../plant/output/leaf_lengths_metabolite.csv") %>%
  mutate(pot=str_pad(pot, width=3, pad="0"),
         sampleID=str_c("wyo", genotype, pot, sep="_")) %>%
  select(sampleID, genotype, trt, leaf_avg_std)
leaflength %>% arrange(sampleID)
```

get and wrangle metabolite data
```{r}
met_raw <-read_csv("../input/metabolites_set1.csv")
met <- met_raw %>% 
  mutate(pot=str_pad(pot, width = 3, pad = "0")) %>%
  mutate(sampleID=str_c("wyo", genotype, pot, sep="_")) %>%
  select(sampleID, genotype, tissue, sample_mass = `sample_mass mg`, !submission_number:concatenate) %>%
  pivot_longer(!sampleID:sample_mass, names_to = "metabolite", values_to = "met_amount") %>%
  
  #remove unnamed metabolites
  filter(str_detect(metabolite, "[A-Z]|[a-z]")) %>%
  
  #adjust by sample mass
  mutate(met_per_mg=met_amount/sample_mass) %>%
  
  #scale and center
  group_by(metabolite, genotype, tissue) %>%
  mutate(met_per_mg=scale(met_per_mg),
         met_amt=scale(met_amount)
  ) %>% 
  pivot_wider(id_cols = sampleID, 
              names_from = c(tissue, metabolite), 
              values_from = starts_with("met_"),
              names_sep = "_")

met 
```

split this into two data frames, one normalized by tissue amount and one not.
```{r}
met_per_mg <- met %>% select(sampleID, starts_with("met_per_mg")) 

met_amt <- met %>% select(sampleID,  starts_with("met_amt"))
```

get leaf data order to match

```{r}
leaflength <- leaflength[match(met$sampleID, leaflength$sampleID),]
leaflength
```

```{r}
met_per_mg <- leaflength %>% left_join(met_per_mg, by="sampleID")
met_per_mg
```

```{r}
met_per_mg_d <- met_per_mg %>% select(-sampleID, -genotype) %>%
  set_names(make.names(colnames(.)))
met_per_mg.fit1 <- brm(leaf_avg_std ~ trt + .,
                      prior = set_prior("lasso(1)"),
                       data=met_per_mg_d)
```

```{r}
fixef(met_per_mg.fit1) %>% as.data.frame() %>% arrange(desc(Estimate))
```

