---
title: "13_metabolite_correlation"
author: "Julin Maloof"
date: "4/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Correlation between root and leaf metabolites

```{r}
library(tidyverse)
```


get and wrangle metabolite data
```{r}
met_raw <-read_csv("../input/metabolites_set1.csv")
met <- met_raw %>% 
  mutate(pot=str_pad(pot, width = 3, pad = "0")) %>%
  mutate(sampleID=str_c("wyo", genotype, pot, sep="_")) %>%
  mutate(trt=ifelse(is.na(autoclave), "BLANK", autoclave)) %>%
  select(sampleID, genotype, tissue, trt, sample_mass = `sample_mass mg`, !submission_number:concatenate)  %>%
  
  #make long
  pivot_longer(!sampleID:sample_mass, names_to = "metabolite", values_to = "met_amount") %>%
  
  #filter away unnamed
  filter(str_detect(metabolite, pattern="^[0-9]+$", negate=TRUE)) %>%
  
  #adjust by sample mass
  mutate(met_per_mg=met_amount/sample_mass) %>%
  
  #scale and center
  group_by(metabolite, genotype, tissue) %>%
  mutate(met_per_mg=scale(met_per_mg),
         met_amt=scale(met_amount)
  ) %>% 
  pivot_wider(id_cols = c(sampleID, genotype, trt), 
              names_from = c(tissue, metabolite), 
              values_from = starts_with("met_"),
              names_sep = "_")

met 
```

```{r}
met_per_mg <- met %>% select(sampleID, genotype, trt, starts_with("met_per_mg")) %>%
  as.data.frame() %>% column_to_rownames("sampleID")
met_amt <- met %>% select(sampleID,  genotype, trt, starts_with("met_amt")) %>%
  as.data.frame() %>% column_to_rownames("sampleID")
```

```{r}
root_leaf_cor <- met %>% select(-starts_with("met_amount")) %>% #colnames()# magrittr::extract(,c(1:4, 345:353)) %>% View()
  pivot_longer(c(-sampleID, -genotype,-trt), 
               names_to = c("norm", "tissue", "met"),
               names_pattern = "met_(amt|per_mg)_(leaf|root)_(.*)") %>%
  pivot_wider(id_cols=c(sampleID, genotype, trt, norm, met), names_from = "tissue", values_from = "value") %>%
  group_by(norm, met) %>%
  summarize(cor_leaf_root=cor(leaf,root))  %>% arrange(norm, desc(cor_leaf_root))
```

```{r}
root_leaf_cor %>% 
  write_csv("../output/met_root_leaf_cor.csv")
```

```{r}
root_leaf_cor %>% ggplot(aes(x=cor_leaf_root)) +
  geom_density(fill="skyblue") +
  facet_grid(~norm)
```

